services:
  - type: web
    name: it-solutions-uganda
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://Vercel-Admin-itsolutions:Mun00nDa5%23%23%23@itsolutions.31hekau.mongodb.net/itsolutions?retryWrites=true&w=majority
      - key: PORT
        value: 10000
